export const items = [
  {
    key: "Header",
    name: "Header Text",
    icon: "fas fa-heading",
    static: true,
    content: "Placeholder Text...",
  },
  {
    key: "Label",
    name: "Label",
    static: true,
    icon: "fas fa-font",
    content: "Placeholder Text...",
  },
  {
    key: "Paragraph",
    name: "Paragraph",
    static: true,
    icon: "fas fa-paragraph",
    content: "Placeholder Text...",
  },
  {
    key: "LineBreak",
    name: "Line Break",
    static: true,
    icon: "fas fa-arrows-alt-h",
  },
  {
    key: "Dropdown",
    canHaveAnswer: true,
    name: "Dropdown",
    icon: "far fa-caret-square-down",
    label: "Placeholder label",
    field_name: "dropdown_",
    options: [],
  },
  {
    key: "Checkboxes",
    canHaveAnswer: true,
    name: "Checkboxes",
    icon: "far fa-check-square",
    label: "Placeholder label",
    field_name: "checkboxes_",
    options: [],
  },
  {
    key: "RadioButtons",
    canHaveAnswer: true,
    name: "Multiple Choice",
    icon: "far fa-dot-circle",
    label: "Placeholder label",
    field_name: "radiobuttons_",
    options: [],
  },
  {
    key: "TextInput",
    canHaveAnswer: true,
    name: "Text Input",
    label: "Placeholder label",
    icon: "fas fa-font",
    field_name: "text_input_",
  },
  {
    key: "EmailInput",
    canHaveAnswer: true,
    name: "Email",
    label: "Placeholder label",
    icon: "fas fa-envelope",
    field_name: "email_input_",
  },
  {
    key: "NumberInput",
    canHaveAnswer: true,
    name: "Number Input",
    label: "Placeholder label",
    icon: "fas fa-plus",
    field_name: "number_input_",
  },
  {
    key: "PhoneNumber",
    canHaveAnswer: true,
    name: "Phone Number",
    label: "Placeholder label",
    icon: "fas fa-phone",
    field_name: "phone_input_",
  },
  {
    key: "TextArea",
    canHaveAnswer: true,
    name: "Multi-line Input",
    label: "Placeholder label",
    icon: "fas fa-text-height",
    field_name: "text_area_",
  },
  {
    key: "TwoColumnRow",
    canHaveAnswer: false,
    name: "Two Column Row",
    label: "",
    icon: "fas fa-columns",
    field_name: "two_col_row_",
  },
  {
    key: "ThreeColumnRow",
    canHaveAnswer: false,
    name: "Three Column Row",
    label: "",
    icon: "fas fa-columns",
    field_name: "three_col_row_",
  },
  {
    key: "Rating",
    canHaveAnswer: true,
    name: "Rating",
    label: "Placeholder label",
    icon: "fas fa-star",
    field_name: "rating_",
  },
  {
    key: "DatePicker",
    canDefaultToday: true,
    canReadOnly: true,
    dateFormat: "MM/dd/yyyy",
    timeFormat: "hh:mm aa",
    showTimeSelect: false,
    showTimeSelectOnly: false,
    showTimeInput: false,
    name: "Date",
    icon: "far fa-calendar-alt",
    label: "Placeholder label",
    field_name: "date_picker_",
  },
  {
    key: "Signature",
    canReadOnly: true,
    name: "Signature",
    icon: "fas fa-pen-square",
    label: "Signature",
    field_name: "signature_",
  },
  {
    key: "HyperLink",
    name: "Web site",
    icon: "fas fa-link",
    static: true,
    content: "Placeholder website Link...",
    href: "http://www.example.com",
  },
  {
    key: "Range",
    name: "Range",
    icon: "fas fa-sliders-h",
    label: "Placeholder label",
    field_name: "range_",
    step: 1,
    default_value: 3,
    min_value: 1,
    max_value: 5,
    min_label: "easy",
    max_label: "difficult",
  },
  {
    key: "Camera",
    name: "Camera",
    icon: "fas fa-camera",
    label: "Placeholder label",
    field_name: "camera_",
  },
  {
    key: "FileUpload",
    name: "File Upload",
    icon: "fas fa-file",
    label: "Placeholder label",
    field_name: "file_upload_",
  },
];
